export const GAME_CONFIGS = {
  BGMI: {
    id: "bgmi",
    name: "BGMI",
    logo: "/images/bgmi-logo.png",
    banner: "/images/bgmi-banner.svg",
    color: "#f97316",
    gradient: "from-orange-500/20 to-yellow-500/10",
    stats: ["kills", "damage", "survivalTime", "rank", "headshot"],
    labels: {
      kills: "Kills",
      damage: "Damage",
      survivalTime: "Survival (min)",
      rank: "Placement",
      headshot: "Headshot %",
    },
    defaults: { kills: 0, damage: 0, survivalTime: 20, rank: 1, headshot: 0 },
    keyStat: "damage",
    description: "Battle royale king — survive and dominate.",
  },
  "Call of Duty": {
    id: "cod",
    name: "Call of Duty",
    logo: "/images/cod-logo.png",
    banner: "/images/cod-banner.svg",
    color: "#22c55e",
    gradient: "from-green-500/20 to-emerald-500/10",
    stats: ["kills", "deaths", "headshot", "accuracy", "score"],
    labels: {
      kills: "Kills",
      deaths: "Deaths",
      headshot: "Headshot %",
      accuracy: "Accuracy %",
      score: "Score",
    },
    defaults: { kills: 0, deaths: 0, headshot: 0, accuracy: 0, score: 0 },
    keyStat: "score",
    description: "Fast-paced warfare — every second counts.",
  },
  Valorant: {
    id: "valorant",
    name: "Valorant",
    logo: "/images/valorant-logo.png",
    banner: "/images/valorant-banner.svg",
    color: "#ef4444",
    gradient: "from-red-500/20 to-pink-500/10",
    stats: ["kills", "deaths", "headshot", "wins", "losses"],
    labels: {
      kills: "Kills",
      deaths: "Deaths",
      headshot: "Headshot %",
      wins: "Wins",
      losses: "Losses",
    },
    defaults: { kills: 0, deaths: 0, headshot: 0, wins: 0, losses: 0 },
    keyStat: "headshot",
    description: "Tactical precision — agents and strategy.",
  },
  CS2: {
    id: "cs2",
    name: "CS2",
    logo: "/images/cs2-logo.png",
    banner: "/images/cs2-banner.svg",
    color: "#3b82f6",
    gradient: "from-blue-500/20 to-cyan-500/10",
    stats: ["kills", "deaths", "accuracy", "mvps", "wins"],
    labels: {
      kills: "Kills",
      deaths: "Deaths",
      accuracy: "Accuracy %",
      mvps: "MVPs",
      wins: "Wins",
    },
    defaults: { kills: 0, deaths: 0, accuracy: 0, mvps: 0, wins: 0 },
    keyStat: "accuracy",
    description: "The pinnacle of tactical FPS — precision is everything.",
  },
  Fortnite: {
    id: "fortnite",
    name: "Fortnite",
    logo: "/images/fortnite-logo.png",
    banner: "/images/fortnite-banner.svg",
    color: "#a855f7",
    gradient: "from-purple-500/20 to-violet-500/10",
    stats: ["kills", "damage", "survivalTime", "rank", "accuracy"],
    labels: {
      kills: "Kills",
      damage: "Damage",
      survivalTime: "Survival (min)",
      rank: "Placement",
      accuracy: "Accuracy %",
    },
    defaults: { kills: 0, damage: 0, survivalTime: 0, rank: 1, accuracy: 0 },
    keyStat: "damage",
    description: "Build, survive, and win — the ultimate battle royale.",
  },
  "Apex Legends": {
    id: "apex",
    name: "Apex Legends",
    logo: "/images/apex-logo.png",
    banner: "/images/apex-banner.svg",
    color: "#f43f5e",
    gradient: "from-rose-500/20 to-red-500/10",
    stats: ["kills", "damage", "survivalTime", "headshot", "wins"],
    labels: {
      kills: "Kills",
      damage: "Damage",
      survivalTime: "Survival (min)",
      headshot: "Headshot %",
      wins: "Wins",
    },
    defaults: { kills: 0, damage: 0, survivalTime: 0, headshot: 0, wins: 0 },
    keyStat: "damage",
    description: "Legend-based battle royale — legends never die.",
  },
};

export const GAME_LIST = Object.keys(GAME_CONFIGS);

export function getGameConfig(gameName) {
  return GAME_CONFIGS[gameName] || GAME_CONFIGS.BGMI;
}

export const DEFAULT_COMPETITIVE_PREFERENCES = {
  role: "IGL",
  trainingFocus: "Aim Mechanics",
  darkMode: true,
  notifications: true,
};
